apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ed-beta
  name: ed-beta-deployment
  namespace: elpis-demo-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ed-beta-pod
  template:
    metadata:
      labels:
        app: ed-beta-pod
    spec:
      containers:
        - image: "g-xuez5266-docker.pkg.coding.net/elpis/elpis-demo-2025/elpis-demo-image-beta"
          name: ed-beta-container
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: coding-registry-cred-9238142
